#pragma once

#include <includes-std.h>
#include <includes-physics.h>
#include <includes-directx.h>
#include <includes-gui.h>
#include <includes-scripts.h>

#include <defines.h>
#include <Singleton.h>

#include <MUtils.h>
#include <MSound.h>
#include <MCore.h>
#include <MLogger.h>
#include <MResProvider.h>
#include <MResLoader.h>
#include <MWindow.h>
#include <MPhysics.h>
#include <MRenderer.h>
#include <MScripts.h>
#include <MHud.h>
#include <MCamera.h>
#include <MInput.h>
#include <MTimer.h>
#include <MTransform.h>
#include <MGameObject.h>
#include <MMesh.h>
#include <MRigidBody.h>
#include <MMaterial.h>
#include <MAssetsDB.h>
#include <MResManager.h>
#include <MWorld.h>
#include <MShader.h>

#include <MLogger.cpp>
#include <MResProvider.cpp>
#include <MResLoader.cpp>
#include <MScripts.cpp>
#include <MWindow.cpp>
#include <MPhysicsErrorReport.cpp>
#include <MPhysicsMemAllocator.cpp>
#include <MPhysics.cpp>
#include <MCore.cpp>
#include <MRendererDriver.cpp>
#include <MRenderer.cpp>
#include <MSound.cpp>
#include <MHud.cpp>
#include <MHudAPI.cpp>
#include <MCamera.cpp>
#include <MInput.cpp>
#include <MTimer.cpp>
#include <MGameObject.cpp>
#include <MTransform.cpp>
#include <MMesh.cpp>
#include <MAssetsDB_Meshes.cpp>
#include <MAssetsDB_GameObjects.cpp>
#include <MAssetsDB_Materials.cpp>
#include <MAssetsDB_Rigids.cpp>
#include <MAssetsDB_Textures.cpp>
#include <MResProvider_MeshObj.cpp>
#include <MResProvider_MeshGLTF.cpp>
#include <MResProvider_Rigids.cpp>
#include <MResProvider_Textures.cpp>
#include <MTexture.cpp>
#include <MGLTFAssetLoader.cpp>
#include <MRigidBody.cpp>
#include <MMaterial.cpp>
#include <MAssetsDB.cpp>
#include <MResManager.cpp>
#include <MWorld.cpp>
#include <MWorld_AssetMain.cpp>
#include <MRegion.cpp>
#include <MShader.cpp>
